### ISSUE TITLE
No annotations in the "Ballerina by example" section

### ISSUE THREAD

**Issue by shagus60** [ballerina-platform/ballerina-examples#1012]

**Comment by ayomawdb** [comment]
Hi @shagus60, Just to be clear, are you looking for an example related to introducing custom annotations to Ballerina and using them to extend some aspects of the Language? 

If not, please correct me. However, assuming that you are expecting such example: 

"Ballerina by examples" section is completely focused on providing examples on how to use Ballerina language features. It is possible to introduce an annotation using Ballerina. However, as of now, in order to process these annotations and act on them, it is required to bring-in a Java based annotation processor. Hence, custom annotations is not a Ballerina "language feature", but an extension mechanism to the compiler, as of now. There is on going discussion on providing APIs to process annotations within Ballerina issue [#10576](https://github.com/ballerina-platform/ballerina-lang/issues/10576) was created to track this.

Given this condition, custom annotation related details are documented separately in "[How to Extend Ballerina](https://ballerina.io/learn/how-to-extend-ballerina/#create-custom-annotations-builder-extensions)" page. I'll close this issue on behalf of issue 10576. Examples and relevant docs will be added with the implementation of the said new feature.
