### ISSUE TITLE
log-api sample failed with CLI

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-examples#214]
**Description:**
As $subject please see below
> [root@ballerinaonrethat3 bin]# ./ballerina run ../../../ballerina/ballerina-examples/examples/log-api/log-api.bal -e [ballerina.log].level=TRACE
', ' 1:15 mismatched input '.' expecting {<EOF>, '	', '
', '
', ' '}
2018-04-18 04:54:34,909 ERROR [] - error log 
2018-04-18 04:54:34,916 ERROR [] - error log with cause : {message:"error occurred", cause:null} 
2018-04-18 04:54:34,917 INFO  [] - info log 

**Affected Product Version:**
ballerina-examples after commit-id (258ce86964f526898f05810c24ced933ef4eccdb)
build pack (ballerina-0.970.0-beta1-SNAPSHOT)

**OS, DB, other environment details and versions:**    
rhel 7.3 | oracle jdk 1.8.0_161

**Comment by dilinisg** [comment]
Observed the same in Windows 10 OS

**Comment by MaryamZi** [comment]
The log flag seems to have been changed from `[ballerina.log].level` to `b7a.log.level` on Apr 10 with https://github.com/ballerina-platform/ballerina-lang/commit/41dd9e8a3e29db2b61387507654cb63f452e9444, and the log BBE description after this issue was created, with 7008e44c49fe05a47fe7bf0ffeb3247563001494.

Closing this issue since running the sample with the new flag does not produce this error, but running with the old flag does.
