### ISSUE TITLE
Logs are not written in the http-access-logs sample

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#295]
**Affected Product Version:**
Ballerina beta 3 nightly

**OS, DB, other environment details and versions:**    
JDK - 1.8.0_171
Windows 10

**Steps to reproduce:**
1. Run the sample with both `-B[accesslog.http].logto=console` and -`B[accesslog.http].logto=path/to/file.txt` options

**Related Issues:**
Logs are not written neither to the console nor the file when invoking the service

**Comment by VijithaEkanayake** [comment]
This is fixed in the code base. Following is the new syntax to start service with write access logs to a file. 

ballerina run http_access_logs.bal -e b7a.http.accesslog.path=/Users/vijitha/dev/ballerina/ballerina-examples/examples/http-access-logs/file.txt

Descriptions have been updated with PR[1].

[1]. https://github.com/ballerina-platform/ballerina-examples/commit/86a5fffb3f096a0fd079d45810bfcf9cd9bf9a0d
