### ISSUE TITLE
grpc_bidirectional_streaming_client.out file details should be updated

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-examples#646]
grpc_bidirectional_streaming_client.out file details should be updated. Currently the out file state to run commands [1] and [2]

[1] ballerina build client
[2] ballerina run client.balx
However, for the test to run I had to give the second command as  ballerina run client without the balx. Best if we can update the documentation with the corrections

**Comment by shavantha** [comment]
Please fix in all grpc sample out files

**Comment by daneshk** [comment]
@shavantha once we build ballerina project, correct way is to run the balx file.
In ballerina, we do support run ballerina code giving the package like (`ballerina run <package_name>`). if we issue this command. bvm internally compile the code and run.

since we already build the project, we don't need to compile the code again. we can run the compiled code using the command,
`ballerina run client.balx`
