### ISSUE TITLE
example: BeforeEach test function output is backwards

### ISSUE THREAD

**Issue by hejunchen** [ballerina-platform/ballerina-examples#946]
**Description:**
I am playing around with the Ballerina examples and I am on the page: https://ballerina.io/learn/by-example/testerina-before-each-test.html
The example shows how to code the test functions with **BeforeEach** annotation. However, when executing the test functions. I expect to see the functions get executed by its order. In fact, the output is backwards. 

```
Compiling tests
    before_each_test.bal
Running tests
    before_each_test.bal
I'm the before function!
I'm in test function 3!
I'm the before function!
I'm in the test function 2!
I'm the before function!
I'm the test function 1!
        [pass] testFunction3
        [pass] testFunction2
        [pass] testFunction1

        3 passing
        0 failing
        0 skipped
```

----------------------------------------------

I expect to see the output to be:

```
testFunction1
testFunction2
testFunction3
```

----------------------------------------------
**I am using "ballerina-0.980.1" for windows.**

**Labels:**
Ballerina Test

**Comment by pranavan15** [comment]
@hejunchen What you are getting is the expected behavior of `testerina`. In order to guarantee the test execution order, you can use the `dependsOn` attribute as explained in this [BBE](https://ballerina.io/learn/by-example/testerina-guarantee-test-execution-order.html). This attribute allows you to ensure that the tests run in the expected order.

**Comment by pranavan15** [comment]
Closing this issue as per the above comment.
